name: CI

on:
  push:
    branches: "main"
    tags: ["*"]
  pull_request:
  release:

jobs:
  test:
    name: Tests on ${{ matrix.os }}
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Spack
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          git clone https://github.com/spack/spack.git
          echo "PATH=${PWD}/spack/bin:${PATH}" >> "${GITHUB_ENV}"
      # Make sure `spack` command works
      - name: Spack version number
        shell: bash
        run: spack --version
      - name: Install Reframe
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          git clone https://github.com/eth-cscs/reframe.git
          cd reframe
          # In README.md we claim compatibility with at least v3.8.0, test that version.
          git checkout v3.8.0
          ./bootstrap.sh
          echo "PATH=${PWD}/bin:${PATH}" >> "${GITHUB_ENV}"
      # Make sure `reframe` command works
      - name: ReFrame version number
        shell: bash
        run: reframe -V
      - name: Install OpenMPI, CMake and extra Python packages
        shell: bash
        run: sudo apt-get install openmpi-bin libopenmpi-dev cmake python3-matplotlib python3-pandas
      - name: Run sample benchmark
        shell: bash
        run: |
          export RFM_CONFIG_FILE="${PWD}/reframe_config.py"
          reframe -v -c examples/sombrero --run --performance-report --system github-actions:default
